# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-27 11:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_project_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Gr0up',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('group_id', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.ManyToManyField(to='index.Project')),
            ],
        ),
        migrations.CreateModel(
            name='Pr0ject',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=64)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Company')),
                ('groups', models.ManyToManyField(to='index.Gr0up')),
            ],
        ),
        migrations.CreateModel(
            name='Us3r',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=64)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Company')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(to='index.User'),
        ),
        migrations.AddField(
            model_name='gr0up',
            name='users',
            field=models.ManyToManyField(to='index.Us3r'),
        ),
    ]
